service: FamilyCarousel-Ui

frameworkVersion: ^3.21.0
configValidationMode: error
deprecationNotificationMode: error

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}  
  region: us-east-1
  logRetentionInDays: 3
  timeout: 29
  memorySize: 1024
  environment:
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1,
    AUTH_DOMAIN: ${self:custom.authDomainMap.${self:provider.stage}}
    AUTH_CLIENT_ID: ${self:custom.authClientIdMap.${self:provider.stage}}
    AUTH_AUDIENCE: ${self:custom.authAudienceMap.${self:provider.stage}}
    LOGOUT_REDIRECT_URL: ${self:custom.logoutRedirectUrlMap.${self:provider.stage}}
  apiGateway:
    shouldStartNameWithService: true
  iam: 
    role:
      statements:
        - Action:
            - lambda:InvokeAsync
            - lambda:InvokeFunction
          Effect: Allow
          Resource: '*'

functions:
  nuxt:
    handler: handler.nuxt
    name: ${self:provider.stage}-familycarousel-nuxt
    description: Aws lambda function servicing up serverless nuxt SSR site for family carousel
    events:
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-plugin-common-excludes
  - serverless-domain-manager
  - serverless-apigw-binary
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - '!src/**'
    - '!.nuxt/**'
    - 'src/static/**'
    - '.nuxt/dist/**'
    # - 'node_modules/@nuxtjs/vuetify/**'
    # - 'node_modules/@nuxtjs/google-gtag/**'
    # - 'node_modules/@nuxtjs/proxy/**'
    # - 'node_modules/@nuxtjs/axios/**'
    # - 'node_modules/@nuxt/image/**'
    # - 'node_modules/nuxt-validate/**'
    # - 'node_modules/vee-validate/**'

custom:
  includeDependencies:
    enableCaching: true
  apigwBinary:
    types:
      - "*/*"
  serverless-offline:
    noPrependStageInUrl: true
  domainMap: 
    dev: dev.familycarousel.com
    prod: familycarousel.com
  certMap:
    dev: '*.familycarousel.com'
    prod: '*.familycarousel.com'
  authDomainMap: 
    dev: familycarousel-dev.us.auth0.com
    prod: familycarousel.us.auth0.com
  authClientIdMap:
    dev: JNJlXp4LPuZ9BNjYVojqQis8QvKf8Fym
    prod: ''
  authAudienceMap:
    dev: https://dev.api.familycarousel.com
    prod: https://api.familycarousel.com
  logoutRedirectUrlMap:
    dev: https://dev.api.familycarousel.com
    prod: https://api.familycarousel.com
  customDomain:
    domainName: ${self:custom.domainMap.${self:provider.stage}}
    endpointType: regional
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
    certificateName: ${self:custom.certMap.${self:provider.stage}}